version: "2.12.2"

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "2000:1433"
    environment:
      SA_PASSWORD: "Pa55word!"
      ACCEPT_EULA: "Y"

volumes:
  rabbitmqdata: