version: "2.12.2"

networks:
  dev:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - dev

  # email_srv:
  #   image: djoufson/sagademo.emailservice
  #   depends_on:
  #     - "rabbitmq"
  #     - "postgres_db"
  #   container_name: sagademo.email-service
  #   ports:
  #     - 5000:80
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - ConnectionStrings__Postgres=User ID=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=EmailService;IntegratedSecurity=true;Pooling=true;
  #     - ASPNETCORE_URLS=http://+:80
  #   networks:
  #     - dev

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGES_PASSWOD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433
    restart: always
    volumes:
      - appdata:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  rabbitmqdata:
  mssqldata:
  appdata:
