apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: djoufson/sagademo.authservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 80
