apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: djoufson/sagademo.emailservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: emailservice
    protocol: TCP
    port: 80
    targetPort: 80
