apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-auth
spec:
  selector:
    matchLabels:
      app: mssql-auth
  template:
    metadata:
      labels:
        app: mssql-auth
    spec:
      containers:
      - name: mssql-auth
        image: mcr.microsoft.com/mssql/server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1433
        volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mypvc
